#!/usr/bin/env bash

# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -eo pipefail # -u breaks python activate scripts

#set -x

# https://stackoverflow.com/a/246128/2895343
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# make venv
python_version="$(python --version || true)"
if (
  echo "${python_version}" \
    | grep -P 'Python 3'
); then
  python -m venv ./cds-wrap-venv
else
  python3 -m venv ./cds-wrap-venv
fi

venv_activated=false

if [[ -d "./cds-wrap-venv/bin" ]]; then
  source ./cds-wrap-venv/bin/activate
  venv_activated=true
fi

if [[ -d "./cds-wrap-venv/Scripts" ]]; then
  source ./cds-wrap-venv/Scripts/activate
  venv_activated=true
fi

if [[ "${venv_activated}" != "true" ]]; then
  echo ERROR:  Failed to activate venv 1>&2
  exit 1
fi

  pip install --upgrade pip \
    || pip install --ignore-installed --upgrade pip
  pip install --upgrade wheel
  # if our script is sitting in a git repo, then install cds-wrap from that repo
  if ( git -C "${script_dir}" rev-parse ) ; then
    pip install --upgrade "${script_dir}"
  # else install default branch from github
  else
    pip install --upgrade "git+https://github.com/gregorydulin/cds-wrap.git"
  fi
deactivate
